### PR TITLE
Cuda debugging

### PR DESCRIPTION
**Pull request by mclarsen**

### CODE REVIEW

**Comment by mclarsen** [comment]
LGTM

**Comment by mclarsen** [comment]
Testing gitlabs CI

**Comment by mclarsen** [comment]
LGTM

**Comment by mclarsen** [comment]
3s30go(1)

**Comment by mclarsen** [comment]
LGTM

**Comment by mclarsen** [comment]
download(1)

**Comment by mclarsen** [comment]
LGTM

**Comment by mclarsen** [comment]
cats

**Comment by maxishii** [comment]
LGTM

**Review by maxishii — APPROVED** [review]

**Pull request merged**
